BEGIN;

--
-- Structure de la table 'pokemon'
--

DROP TABLE IF EXISTS "pokemon";

CREATE TABLE "pokemon" (
   "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
   "nom" TEXT NOT NULL,
   "pv" INT NOT NULL,
   "attaque" INT NOT NULL,
   "defense" INT NOT NULL,
   "attaque_spe" INT NOT NULL,
   "defense_spe" INT NOT NULL,
   "vitesse" INT NOT NULL,
   "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   "updated_at" TIMESTAMPTZ

);

-- --------------------------------------------------------

--
-- Structure de la table 'type'
--

DROP TABLE IF EXISTS "type";

CREATE TABLE "type" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "color" VARCHAR(6) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);


-- --------------------------------------------------------

--
-- Structure de la table 'pokemon_has_type'
--
DROP TABLE IF EXISTS "pokemon_has_type";

CREATE TABLE "pokemon_has_type" (
    "id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    "pokemon_id" INT NOT NULL REFERENCES "pokemon" ("id"),
    "type_id" INT NOT NULL REFERENCES "type" ("id"),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ
);

COMMIT;